name: GeoWarp
main: GeoWarp
version: 1.0.0
api-version: "1.21"
commands:
  warp:
    description: Warp mit Anchors, Listen, Add & Remove
    usage: |
      /warp <Land> [Stadt] [Straße] [Hausnr]
      /warp add <Land> [Stadt] [Straße] [Hausnr]
      /warp remove <Land> [Stadt] [Straße] [Hausnr]
      /warp list [Land] [Stadt] [Straße]
      /warp export
    permission: warp.use
permissions:
  warp.use: { default: true }
  warp.admin: { default: op }
